/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in many projects. It teaches TypeScript
// about Next-specific imports and should not be edited by hand after setup.
